### ISSUE TITLE
Feature request: Enter a value directly on the Extra Control "Spin Box".

### ISSUE THREAD

**Issue by hellishvictor** [pedrolcl/VMPK#12]
Hi, when is added a "Spin Box", it's not possible enter directly a value in the box, (even though that "Enable Computer Keyboard Input" if off), but only is allowed to use the arrows up and down. Implementing this little thing will really speed up the workflow.
Cheers.

**Comment by pedrolcl** [comment]
Yes, this is a consequence of this line:
https://github.com/pedrolcl/VMPK/blob/3e2616bc85c63e71957c149e3af92e4b27c9a296/src/vpiano.cpp#L582

The reason is: every widget on the window has `setFocusPolicy(Qt::NoFocus)` to avoid interfering with the piano keyboard focus. This way, when the VMPK window has the focus, the piano control is always focused (which means: gets the computer keyboard events). Only a single widget in the whole application can have the keyboard focus at a time.

But there is a workaround (sort of): you may use the Controller Up/Down shortcuts if you need (which by default are  "Alt+" and "Alt-"). For instance, if you add an extra controller named "Phaser", MIDI controller 95, type "spinbox"...
![image](https://github.com/pedrolcl/VMPK/assets/15184708/47e9d6a8-1f65-4ca6-ad3e-dee4a52b5018)
Now select in the "Controllers" toolbar combo: "95-Phaser depth", and when using the keyboard shortcut "Alt+" and "Alt-", both the extra spinbox and the controller dial will change at the same time.
![image](https://github.com/pedrolcl/VMPK/assets/15184708/a03359d0-b26c-4bc4-8775-52860717ac13)

All keyboard shortcuts are fully configurable. And some extra controls (type button) can have a special shortcut defined, too.

**Comment by hellishvictor** [comment]
Man, I don't use at all the "Controllers" toolbar, I have it always hidden, and I use more than a dozen of spinboxes because they displays the exact values just looking at UI (not like the knobs); I just want to click one of them and enter a value. The only workaround that make sense for me is use the "Edit" button, and it shows the window "Extra Controller Editor" (for which the piano control is disabled/not focused), select one of the Controllers and then is possible to enter directly the values on any of its boxes:
![sshot-2](https://github.com/pedrolcl/VMPK/assets/34694956/83ec76fc-fd78-4110-b3bb-c70c81ab6ec8)

Have you checked Blue Cat's "Remote Control"? It display the value below the knobs, and double clicking on it allows to enter a value on a floating little window disabling the piano control, which is what "Edit" does.
![sshot-1](https://github.com/pedrolcl/VMPK/assets/34694956/e46cc1f1-4f9e-4831-8e93-10a0c469c734)

Well, thank you anyway.

**Comment by pedrolcl** [comment]
In the future, when you ask for a feature request in an open source project, try to justify it thinking on a common use case for most users. That way, the request may be accepted. 

If it is a particular use case that nobody else cares about, then you may simply fork the project and implement your feature by yourself.

**Comment by hellishvictor** [comment]
Sorry, but I cannot go learning all the programming languages that are out there. And that has a common use, that is why is implemented by others (as Blue Cat Audio), but it's not my fault that you don't want to enhance you programs and go several versions with bugs without fix. You're the one who should have more common sense at the time of develop a program.
Thank you anyway,
